# Generated by Django 3.0.6 on 2020-05-18 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0004_auto_20200518_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Metascore',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='Year',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movie',
            name='imdbRating',
            field=models.CharField(max_length=255),
        ),
    ]
