# Generated by Django 3.0.6 on 2020-05-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0006_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_on',
            field=models.DateField(),
        ),
    ]
