# Generated by Django 3.0.6 on 2020-05-18 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_api', '0008_auto_20200518_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='added_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
